<?php


namespace app\admin\controller;


use think\Controller;
use think\Session;

class Base extends Controller
{

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        global $id;
       $id= Session::get('user_id');
    }

    protected function isLogin()
    {
        $id=Session::get('user_id');
        if (empty($id)) {
            $this->error('用户未登录,无法访问',url('user/login'));
        }
    }

    protected function alreadyLogin()
    {
        $id=Session::get('user_id');
        if (!empty($id)) {
            $this->error('用户已登录，不要反复登录',url('index/index'));
        }
    }

}